# Site settings
title: Matt Joseph
email: 
description: > # this means to ignore newlines until "baseurl:"
  Website Matt Joseph (devadvance), including a profile, coding projects, and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mattj.io" # the base hostname & protocol for your site
twitter_username: mattjoseph0
github_username:  devadvance

# Build settings
markdown: kramdown
highlighter: rouge
