# Site settings
title: Matt Joseph
email: 
description: > # this means to ignore newlines until "baseurl:"
  Personal site for Matt Joseph, including a profile, coding projects, and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matthewgjoseph.com" # the base hostname & protocol for your site
twitter_username: devadvance
github_username:  devadvance

# Build settings
markdown: kramdown
highlighter: rouge
