# Site settings
title: Matt Joseph
email: 
description: > # this means to ignore newlines until "baseurl:"
  Homepage of Matt Joseph (devadvance), including a profile, software projects, photography, and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mattj.io" # the base hostname & protocol for your site
twitter_username: mattjoseph0
github_username:  devadvance

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  posts:
    output: true
    permalink: /posts/:year-:month-:day-:title/